blogapp/urls.py
from django.urls import path
from .views import home_view,registration_view,login_view
from .views import create_view,detail_view,logout_view,comment_view




app_name = 'blogapp'
urlpatterns = [
  path("",home_view,name='home'),
  path("register",registration_view,name='register'),
  path("login",login_view,name='login'),
  path("logout",logout_view,name='logout'),
  path("create",create_view,name='create'),
  path("<int:id>",detail_view,name='detail'),
  path("<int:article_id>/",comment_view,name='comment'),
  # path("<int:delete_id>/",commentdelete_view,name='commentdelete'),
  




]

blogproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogapp.urls')),


]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Timestamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Admin(Timestamp):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='admin')

    def save(self, *args, **kwargs):
        grp, created = Group.objects.get_or_create(name='admin')
        self.user.groups.add(grp)

        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Blogger(Timestamp):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=50)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    photo = models.ImageField(upload_to='customer', null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        grp, created = Group.objects.get_or_create(name='blogger')
        self.user.groups.add(grp)

        super().save(*args, **kwargs)

class Article(Timestamp):
	title=models.CharField(max_length=200)
	slug=models.SlugField(unique=True)
	image=models.ImageField(upload_to='blogs')
	content=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	author=models.ForeignKey(User,on_delete=models.CASCADE)
	views=models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.title
	"""docstring for """

class Comment(Timestamp):
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    commenter=models.ForeignKey(User,on_delete=models.CASCADE)
    text=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    root=models.ForeignKey("self",on_delete=models.CASCADE,null=True,blank=True)
    #self le chai Comment lai call gareko ho 

    def __str__(self):
        return " comment for "+ self.article.title + " by " + self.commenter.username	 

class ArticleImage(Timestamp):
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="blog/images")
    comment=models.ForeignKey(Comment,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.article.title               

blogapp/forms.py
from django import forms 
from .models import Blogger,Article,Comment
from django.contrib.auth.forms import UserCreationForm

from django.forms import ModelForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
	class Meta:
		model=User

		fields=["username","email","password1","password2"]


class BlogForm(forms.ModelForm):
    images=forms.FileField(widget=forms.FileInput(attrs={
        "multiple":True}))
    
    class Meta:

        model = Article
        fields = ['title', 'images','slug', 'content', 'views']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]
        widgets = {
            "text": forms.Textarea(attrs={
                "rows": 3,
                "class": "form-control",
                "placeholder": "Write your Comment"
            })
        }        

blogapp/views.py
from django.shortcuts import render,redirect
from django.views.generic import *
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from .models import Admin,Blogger,Article,Comment,ArticleImage
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout, authenticate, login
from .forms import CreateUserForm,BlogForm,CommentForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def home_view(request):
    articlelist=ArticleImage.objects.all()
    context={
             'list':articlelist,
    }


    return render(request, "home.html",context)

def registration_view(request):
    form=CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user=form.cleaned_data.get("username")
            messages.success(request,"Account was successfully registered"+user)

        return redirect('blogapp:login')    

    context={"form":form}
    return render(request,'register.html',context)

def login_view(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    print(username)
    print(password)
    user = authenticate(request,username=username,password=password)
    print(user)
    if user is not None:
        login(request,user)
        print('login successfull')
        return redirect('/')

    return render(request,'login.html')    

def logout_view(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("/")

@login_required
def create_view(request):
    # add the dictionary during initialization 
    form = BlogForm(request.POST,request.FILES or None)
    context={}

    if form.is_valid(): 
        logged_in_user = request.user
        form.instance.author = logged_in_user
        artobj=form.save()

        uploaded_images=request.FILES.getlist("images")

        for img in uploaded_images:
            ArticleImage.objects.create(article=artobj,image=img)
         
        return redirect("/")
          
    context['form']= form 
    return render(request, "create.html", context) 

@login_required
def detail_view(request,id):
    form=CommentForm()
    articlelist=ArticleImage.objects.get(id=id)
    comment=articlelist.comment.all()
    context={
             'detail':articlelist,
             'comments':form,
             'commentss':comment,
    }

    return render(request, "detail.html",context)

@login_required
def comment_view(request,article_id):
    print(article_id)
    if request.method=='POST':
        print(request.POST['text'])
        form=CommentForm(request.POST)
        if form.is_valid():
            form.instance.article = Article.objects.get(id=article_id)
            form.instance.commenter = User.objects.get(username=request.user.username)
            form.save()
            return HttpResponseRedirect(reverse('blogapp:detail',kwargs={'id':article_id}))
        # form.instance.article=Article.objects.get(id=id)
        # form.instance.commenter=User.objects.get(user=request.user)
        # form.instance.text=request.POST['text']

        # form.save()
    else:
        form=CommentForm()
        articlelist=ArticleImage.objects.get(id=id)
        context = {
            'comments':form,
            'detail':articlelist,
        }

    return render(request,"detail.html",context) 

# def commentdelete_view(request,delete_id):

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
 <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>CosmioBlog</title>
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <!-- Css -->
          <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
          <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
          <link
               href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
               rel="stylesheet"
               integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
               crossorigin="anonymous">

          <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
          <link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>     
          <!-- font awasome font -->
          <link rel="stylesheet"
               href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
          <!-- owl carousel -->
          <link rel="stylesheet" href="../assets/css/owl.carousel.css">
          <link rel="stylesheet" href="../assets/css/owl.theme.default.css">
          <!-- stlyle css -->
          <link rel="stylesheet" href="../assets/css/style.css">


          <!-- JS -->
          <script src="https://code.jquery.com/jquery-3.4.1.min.js"
               integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>
          <script
               src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
               integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
               crossorigin="anonymous">

     </script>
          <script
               src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/popper.min.js"
               integrity="sha256-5svdPV/pJHGKdkwy2zo8jfH1925FafkffDDabT2cEBk="crossorigin="anonymous"></script>
          <!-- owl carousel -->
          <script src="../assets/js/owl.carousel.min.js"></script>
          <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  
     </head>
     <style>
     	.navbar {
  background-color: transparent;
  border-bottom: 0.5px solid black;
  z-index: 2;
}
.container-fluid {
  background-color: black;
  height: 50px;
  text-align: center;
}
.container-fluid ul {
  list-style: none;
}
.container-fluid ul li {
  float: left;
  color: wheat;
  font-size: 14px;
}
.email {
  padding-left: 50px;
}
.bold {
  font-weight: bold;
  font-size: 18px;
}
.social {
  float: right;
  padding-left: 5px;
}
.navbar-light {
  padding-left: 50px;
  background-color: white;
}
.navbar-light .navbar-brand {
  color: red;
  font-weight: bold;
  font-size: 20px;
}
.navbar-light .navbar-nav .nav-link {
  color: #33333f;
  padding-left: 30px;
}
.navbar-light .navbar-nav .nav-link:hover {
  color: red;
  opacity: 1;
  text-decoration: underline;
}
.navbar-light .navbar-text {
  margin-right: 30px;
}
</style>

     <body>
          <!-- <div class="container-fluid py-3 px-5 small font-weight-bold">
          <ul>
               <li><span class="bold">Contact Us:</span> 9800000</li>
               <li class="email"> <span class="bold">Email:</span> gmail@mail.com</li>
          </ul>
          <img class="rounded-circle social" alt="image" height="30" src="../assets/image/twiter.png" href="#">
          <img class="rounded-circle social" alt="image" height="30" src="../assets/image/insta.jpg" href="#">
          <img class="rounded-circle social" alt="image" height="30" src="../assets/image/facebook-new.png" href="#">

     </div> -->
          <nav class="navbar navbar-expand-lg navbar-light" style="position:
               sticky; top: 0;">
               <a class="navbar-brand realstate" href="/">CosmioBlog</a>
               <button class="navbar-toggler" type="button"
                    data-toggle="collapse" data-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse py-0" id="navbarText">
                    <ul class="navbar-nav mr-auto">
                         <li class="nav-item">
                              <a class="nav-link" href="#">Buy <span
                                        class="sr-only">(current)</span></a>
                         </li>
                         <li class="nav-item">
                              <a class="nav-link" href="#">Properies</a>
                         </li>
                         <li class="nav-item">
                              <a class="nav-link" href="#">Agencies</a>
                         </li>
                         <li class="nav-item">
                              <a class="nav-link" href="#">Requirements</a>
                         </li>
                         {% if request.user.is_authenticated %}
                         <li class="nav-item">
                              <a class="nav-link" href="{% url 'blogapp:login' %}"></a>
                              <a class="nav-link" href="{% url 'blogapp:logout' %}">logout</a>

                         
                          {% else %}
                          
                              <a class="nav-link" href="{% url 'blogapp:login' %}">login</a>
                              <a class="nav-link" href="{% url 'blogapp:register' %}">registration</a>
                         </li>
                         {% endif %}

                    </ul>

               </div>
          </nav>
  {% block content %}

  {% endblock %}

  <script src="{% static 'static/js/jquery.min.js' %}"></script>

  <script src="{% static 'static/js/bootstrap.bundle.min.js' %}"></script>

  <script src="{% static 'static/js/scripts.js' %}"></script>







</body> 
</html>

templates/create.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<form method="POST" enctype="multipart/form-data"> 
  
    <!-- Security token -->
    {% csrf_token %} 
  
    <!-- Using the formset -->
    {{ form.as_p }} 
      
    <input type="submit" value="Submit"> 
</form> 

{% endblock %}

templates/detail.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<h1>Title: {{detail.article.title}}</h1>
<img style='width:1000px;height:500px;' src="{{detail.image.url}}">
<p>Detail: {{detail.article.content}}</p>
<p>Author: {{detail.article.author}}</p>


<h3>Comment Form</h3>

	{% if request.user.is_authenticated %}
		<form method="POST" action="{% url 'blogapp:comment' detail.pk %}">
			{% csrf_token %}
			{{comments.as_p}}
			<button class="btn btn-primary">Submit data</button>
		</form>
	{% endif %}	 
		<h4>All Comments</h4>
		{% for comment in commentss %}
		 <li>{{comment.text}}</li>
		 <p style="color: #582703;">by {{comment.commenter.username}} {{comment.date|timesince}} ago</p>
		{% endfor %} 
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
	
<h3>BlogList</h3>
<a href="{% url 'blogapp:create' %}">create</a> 
<div class="row">
{% for lists in list %}
	<div class="col-md-4 mt-3 mb-3">
		<div class="card" style="width: 350px;">
			{% if lists.image %}
			<img class="card-img-top" src="{{lists.image.url}}" alt="img-fluid img-thumbnail" style="height: 250px;object-fit: cover; width: 350px;">
			{% else %}
			<p>No image found!</p>

			{% endif %}
			<div class="card-body">
				<h5 class="card-title"><a style="text-decoration: none !important" href="{% url 'blogapp:detail' lists.id %}">{{lists.article.title}}</a></h5>
				<h5 class="card-title"><a style="text-decoration: none !important" href="">{{lists.article.author}}</a></h5>
			</div>
		</div>
	</div>
     

{% endfor %}
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: linen  !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: maroon;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: linen !important;
			color: red!important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
		.links{
			color: white;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
					{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control" id="username">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" id="password">
						</div>
						{% for message in messages %}
						   <p>{{message}}</p>
						{% endfor %}   

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links ">
						Don't have an account? <a href="{% url 'blogapp:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background:linen !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: maroon;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: linen!important;
			color: red !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
	    .links{
			color: white;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
				{{forms.errors}}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'blogapp:login' %}" class="ml-2">login</a>
					</div>
			
				</div>
		

			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>	


{% endblock %}